### ISSUE TITLE
Cors issue

### ISSUE THREAD

**Issue by donmbelembe** [eusonlito/Password-Manager-Chrome#1]
Access to fetch at 'https://passwords.domain.com/app/api/search' from origin 'https://site.com' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by eusonlito** [comment]
`https://password.domain.com` is an example, you must use your own server endpoint like `https://site.com`.

**Comment by donmbelembe** [comment]
Of course i also replaced my domain because i didn't wanted to expose it. I'm having cors issues

**Comment by eusonlito** [comment]
Response `Access-Control` headers as sent as https://github.com/eusonlito/Password-Manager/blob/master/public/.htaccess:

```
Header set Access-Control-Allow-Origin "*"
Header set Access-Control-Allow-Methods "GET,PUT,POST,DELETE,PATCH,OPTIONS"
Header set Access-Control-Allow-Headers "Accept, Accept-Language, Authorization, Cache-Control, Content-Disposition, Content-Type, Origin, User-Agent, X-Requested-With"
Header set Access-Control-Allow-Credentials "true"
Header set Access-Control-Expose-Headers "Content-Disposition"
Header set Access-Control-Max-Age "86400"
```

Do you are receiving this headers on response?

**Comment by donmbelembe** [comment]
I think the request is not even being made

[DELETED]

**Comment by eusonlito** [comment]
Video deleted to protect your privacy.

Your installed environment `https://passwords.XXXXX.com` is running well with the backend https://github.com/eusonlito/Password-Manager?

**Comment by donmbelembe** [comment]
Yes the backend is working perfectly but i think i have to add the access control headers in the nginx config because nginx doesn't read .htaccess, I'm coming back to you

**Comment by eusonlito** [comment]
Yes, you need to setup the `Access-Control` as apache .htaccess:

```
add_header Access-Control-Allow-Origin "*" always;
add_header Access-Control-Allow-Methods "GET,PUT,POST,DELETE,PATCH,OPTIONS" always;
add_header Access-Control-Allow-Headers "Accept, Accept-Language, Authorization, Cache-Control, Content-Disposition, Content-Type, Origin, User-Agent, X-Requested-With" always;
add_header Access-Control-Allow-Credentials "true" always;
add_header Access-Control-Expose-Headers "Content-Disposition" always;
add_header Access-Control-Max-Age "86400" always;
```
Also, you can improve the `OPTIONS` request with a fast accepted empty request:

```
if ($request_method = "OPTIONS") {
        add_header Access-Control-Max-Age 1728000;
        add_header Content-Type "application/json; charset=UTF-8";
        add_header Content-Length 0;

        return 204;
}
```

**Comment by donmbelembe** [comment]
It kinda worked, the credentials was retrieved successfully but when I'm trying to click to user or password button I'm getting a cors issue again. 

Look at my response
```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, PUT, POST, DELETE, HEAD, OPTIONS, PATCH, PROPFIND, PROPPATCH, MKCOL, COPY, MOVE, LOCK
Access-Control-Allow-Origin: https://edgilitys.com
allow: POST
cache-control: no-cache, private
content-encoding: gzip
content-type: text/html; charset=UTF-8
date: Mon, 04 Oct 2021 07:41:53 GMT
server: nginx/1.18.0 (Ubuntu)
```

**Comment by donmbelembe** [comment]
/api/search endpoint is working but app/api/2/payload/password and app/api/2/payload/user is not working

**Comment by eusonlito** [comment]
And the error is same as before?

1. No header `Access-Control-Allow-Headers` is on response.
2. Header `Access-Control-Allow-Origin` must be `*` because every app has a different URL.

**Comment by donmbelembe** [comment]
1. Access-Control-Allow-Headers is set on the nginx config but it doesn't show on the response
2. of course Access-Control-Allow-Origin is set to * in the nginx server. that is just the response

**Comment by eusonlito** [comment]
Do you use `always` on all `add_header`?

```
add_header Access-Control-Allow-Origin "*" always;
```

**Comment by donmbelembe** [comment]
No. Should I ?

**Comment by eusonlito** [comment]
Yes, some other configurations could overwrite this value.
