### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by cristian-araujo** [eusonlito/Password-Manager-Chrome#2]
I think this not work with 2FA? it doesn't show any data on the chrome extension and every time I open the popup for search data my current session in the backend is closed showing me the 2FA login.

**Comment by eusonlito** [comment]
Chrome extension is not related with 2FA. Are you using the correct endpoint (https://XXXX.com) and API KEY in chrome extension options? Can you see the API requests on Dev Tools?

**Comment by cristian-araujo** [comment]
> Chrome extension is not related with 2FA. Are you using the correct endpoint (https://XXXX.com) and API KEY in chrome extension options? Can you see the API requests on Dev Tools?

I mean the 2FA from the backend, I enabled it but the chrome extension can connect to backend:

```
Request URL: https://xxxxx/app/api/search
Request Method: POST
Status Code: 200 OK
Remote Address: xxxxx
Referrer Policy: strict-origin-when-cross-origin
```

`return []`

after I open the chrome extension I reload the backend page and it inmediatly redirect me to 2FA login

I can make a video if you need

**Comment by eusonlito** [comment]
Maybe some CORS problem as https://github.com/eusonlito/Password-Manager-Chrome/issues/1 ?

**Comment by cristian-araujo** [comment]
I think it's not the problem because when you got a CORS in the dev tools you get an error on the request but my json return empty from the chrome extension.

**Comment by eusonlito** [comment]
And you don't get any error on dev tools (CORS, javascript, etc...)?

**Comment by cristian-araujo** [comment]
No, only the headers I posted

![image](https://user-images.githubusercontent.com/72935660/147103977-6b66a120-a5ff-4c00-bbfb-428bcd5d8689.png)

**Comment by eusonlito** [comment]
Yes, it's right, because you don't have added any app with same domain as the site when you open the extension. But extension it self show any message?

**Comment by cristian-araujo** [comment]
ok, it's was my bad, i didn't understand how it worked, the chrome extension is only for web passwords and not for any other information type like ssh or servers.

I was thinking it worked like a shortcut of the app.

anyway I still continue getting the same error about the auth, when I open the chrome extension my backend session is closed and redirected me to 2FA login page.

**Comment by eusonlito** [comment]
Yes, chrome extension only works for websites.

It's strange, 2FA only show if session id is refreshed:

Set 2FA id on session:

https://github.com/eusonlito/Password-Manager/blob/414643d1602ab91b82df47e5f68fef5f1424becd/app/Domains/User/Action/AuthTFA.php#L61-L67

Session check:

https://github.com/eusonlito/Password-Manager/blob/414643d1602ab91b82df47e5f68fef5f1424becd/app/Domains/User/Action/SessionTFA.php#L29-L35

Are you using multiple users?

**Comment by cristian-araujo** [comment]
No, actually I have only one user in the app

**Comment by eusonlito** [comment]
Can you help me to debug your problem?

Adding this line before https://github.com/eusonlito/Password-Manager/blob/414643d1602ab91b82df47e5f68fef5f1424becd/app/Domains/User/Action/AuthTFA.php#L66

```
\Illuminate\Support\Facades\Log::info([ __CLASS__ => $this->request->session()->getId()]);
```

Adding this line before https://github.com/eusonlito/Password-Manager/blob/414643d1602ab91b82df47e5f68fef5f1424becd/app/Domains/User/Action/SessionTFA.php#L34

```
\Illuminate\Support\Facades\Log::info([ __CLASS__ => $this->request->session()->getId()]);
```

Check the laravel log in `storage/logs`.

The `id` value should be same on two actions.

**Comment by cristian-araujo** [comment]
Sure,

The first one is when I refresh the app

```
[2021-12-22 16:09:20] production.INFO: array (
  'App\\Domains\\User\\Action\\SessionTFA' => 'DEeLPnHNtX2uDa7b20teMARWzn9fMuZUAokTMIMM',
)  
[2021-12-22 16:09:37] production.INFO: array (
  'App\\Domains\\User\\Action\\SessionTFA' => '4ID4PQiXoXfQ2AmQp0edAdtK9n8rprrVurhQJncJ',
)  
```

And the last one is when I open the chrome extension and refresh the page again.

**Comment by eusonlito** [comment]
Ok, maybe Laravel is refreshing sessions internally and this action update the session id.

What about require 2FA every user IP change?

**Comment by cristian-araujo** [comment]
what do you mean? when I tested it my ip was not changed

**Comment by eusonlito** [comment]
Yes, I know, now the 2FA check session ID value, but Laravel can refresh this value on background on same user session, then I can update code to request the 2FA change on IP change instead session id change.

**Comment by eusonlito** [comment]
I have updated app with IP/TTL check instead session id: https://github.com/eusonlito/Password-Manager/commit/bbc529bc7c0406d9ba453809c1bedeb2006bc43f

Please, check if works.

Regards.

**Comment by cristian-araujo** [comment]
I can check it but I think it's not a good idea, many people has dynamic ip for example my ip can change many times in a day or in a hour.

**Comment by eusonlito** [comment]
Yes, I know, the IP check include a 6 hours TTL. After every 2FA request, there are a 6 hours margin before to ask to code again.

**Comment by cristian-araujo** [comment]
> Yes, I know, the IP check include a 6 hours TTL. After every 2FA request, there are a 6 hours margin before to ask to code again.

that's great.

I have tested it and work like a charm, now the chrome extension doesn't close my backend app.

Thank you very much for the help.
