### ISSUE TITLE
Extension keeps loading

### ISSUE THREAD

**Issue by Sogrea** [eusonlito/Password-Manager-Chrome#4]
Hi!

Really appreciate the work done with the project!

As the title says my extension, installed via chrome web store, keeps loading (with the 3 dots circling around), but can't load anything.

I have the application running on a local IP through docker (with the explicit port :8080), so I guess that could be a problem.

**Comment by eusonlito** [comment]
Hello! do you get some developer console error? Can you inspect the extension worker? Right click in extension > Manage Extension > Inspect views.

**Comment by Sogrea** [comment]
![Screenshot 2024-10-15 140022](https://github.com/user-attachments/assets/f62fdf20-2640-477e-944b-a817a50f21d7)

This is the screenshot from the browser console.

I can also see form the network tab that it may be a cors error?

![immagine](https://github.com/user-attachments/assets/f7f4def1-09e7-42ee-a324-d2f9663f1da9)

[EDIT]
After posting this I noticed the endpoint was set with https, and the "Go to web panel" button was not working. After updating with http, the button started working, but i stiill have errors

![immagine](https://github.com/user-attachments/assets/fa68926e-7c57-4be1-90d5-796299d65666)

![immagine](https://github.com/user-attachments/assets/1ae28ecd-7de3-40cb-b264-955c6163766d)

**Comment by eusonlito** [comment]
Ok, is not possible to do a http request from https. You need to add a https proxy (with nginx or apache) in front your http docker endpoint.
